import { PrismaClientKnownRequestError } from "@prisma/client/runtime/client";
import { ERROR_CODES } from "./errorCodes";

const PRISMA_ERROR_MAP: Record<string, string> = {
  P2000: ERROR_CODES.STRING_EXCEEDS_LENGTH,
  P2002: ERROR_CODES.DB_UNIQUE_CONSTRAINT,
  P2003: ERROR_CODES.DB_FOREIGN_KEY_CONSTRAINT,
  P2004: ERROR_CODES.DB_INVALID_QUERY,
  P2005: ERROR_CODES.INVALID_INPUT_FORMAT,
  P2006: ERROR_CODES.INVALID_INPUT_FORMAT,
  P2007: ERROR_CODES.DB_INVALID_QUERY,
  P2008: ERROR_CODES.DB_INVALID_QUERY,
  P2009: ERROR_CODES.DB_INVALID_QUERY,
  P2010: ERROR_CODES.DB_INVALID_QUERY,
  P2011: ERROR_CODES.REQUIRED_FIELD_MISSING,
  P2012: ERROR_CODES.REQUIRED_FIELD_MISSING,
  P2014: ERROR_CODES.DB_INVALID_RELATION,
  P2015: ERROR_CODES.DB_RECORD_NOT_FOUND,
  P2016: ERROR_CODES.DB_RECORD_NOT_FOUND,
  P2017: ERROR_CODES.DB_INVALID_RELATION,
  P2018: ERROR_CODES.DB_INVALID_RELATION,
  P2019: ERROR_CODES.INVALID_INPUT_FORMAT,
  P2020: ERROR_CODES.INVALID_INPUT_FORMAT,
  P2021: ERROR_CODES.DB_INVALID_QUERY,
  P2022: ERROR_CODES.DB_INVALID_QUERY,
  P2023: ERROR_CODES.DB_VALIDATION_ERROR,
  P2024: ERROR_CODES.DB_CONNECTION_ERROR,
  P2025: ERROR_CODES.DB_RECORD_NOT_FOUND,
  P2026: ERROR_CODES.DB_CONNECTION_ERROR,
  P2027: ERROR_CODES.DB_TRANSACTION_FAILED,
  P2028: ERROR_CODES.DB_CONNECTION_ERROR,
  P2030: ERROR_CODES.DB_INVALID_QUERY,
  P2031: ERROR_CODES.DB_TRANSACTION_FAILED,
  P2032: ERROR_CODES.DB_CONNECTION_ERROR,
  P2033: ERROR_CODES.DB_RECORD_LOCKED,
};

export const mapPrismaError = (error: unknown): string => {
  if (error instanceof PrismaClientKnownRequestError) {
    return PRISMA_ERROR_MAP[error.code] ?? ERROR_CODES.DB_INVALID_QUERY;
  }
  return ERROR_CODES.DB_INVALID_QUERY;
};